[package]
name = "chip8"
version = "0.1.0"
authors = ["kelsey <kgregware@umass.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.12"
regex = "0.1.41"
rand = "0.8.2"
sdl2 = "0.34.3"